trigger:
  branches:
    include:
      - master
      - refs/tags/*

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    customTag: 'latest'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    customTag: $(Build.SourceBranchName)

pool:
  name: 'AnonifyDev'

steps:
- task: Docker@2
  displayName: Build and Push image
  inputs:
    command: buildAndPush
    containerRegistry: anonify-ci-cd-acr
    repository: deployer
    tags: $(customTag)
    dockerfile: Dockerfile
    buildContext: .
- script: docker image prune -f
  displayName: Remove dangling images

# TODO: deploy contracts and store the contract address
