[package]
name = "eth-deployer"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
web3 = "0.16"
tokio = { version = "1.0.1", features = ["full"] }
anyhow = "1.0"
ethabi = "14.1.0"
lazy_static = "1.4"
