[package]
name = "eth-deployer"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
web3 = "0.14"
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
ethabi = "12.0.0"
lazy_static = "1.4"
