name: CI testing for topic branchs

on: push

jobs:
  branch-test:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Run tests"
      run: |
        docker-compose up -d
        ./test.sh
    - name: "Shutdown"
      if: always()
      run: |
        docker-compose down
